arch/um: Add a dummy <asm/cacheflush.h> header
... in order to fix the defconfig build:

  ./arch/x86/include/asm/cacheflush.h: In function ‘l1d_flush_hw’:
  ./arch/x86/include/asm/cacheflush.h:15:6: error: implicit declaration of \
	  function ‘static_cpu_has’; did you mean ‘static_key_false’? [-Werror=implicit-function-declaration]

[ mingo: Changed the header guard to the existing nomenclature. ]

Fixes: a9210620ec36 ("x86/mm: Optionally flush L1D on context switch")
Reported-by: Ingo Molnar <mingo@kernel.org>
Signed-off-by: Borislav Petkov <bp@suse.de>
Signed-off-by: Ingo Molnar <mingo@kernel.org>
Link: https://lore.kernel.org/r/20200922074951.2192-1-bp@alien8.de