counter: intel-qep: Fix build error when !CONFIG_PM_SLEEP && CONFIG_PM
Fix following build error when CONFIG_PM is set but CONFIG_PM_SLEEP is
not:

drivers/counter/intel-qep.c:694:21: error: ‘intel_qep_runtime_suspend’ undeclared here (not in a function); did you mean ‘intel_qep_function_set’?
  694 |  SET_RUNTIME_PM_OPS(intel_qep_runtime_suspend, intel_qep_runtime_resume,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/pm.h:342:21: note: in definition of macro ‘SET_RUNTIME_PM_OPS’
  342 |  .runtime_suspend = suspend_fn, \
      |                     ^~~~~~~~~~
drivers/counter/intel-qep.c:694:48: error: ‘intel_qep_runtime_resume’ undeclared here (not in a function)
  694 |  SET_RUNTIME_PM_OPS(intel_qep_runtime_suspend, intel_qep_runtime_resume,
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/pm.h:343:20: note: in definition of macro ‘SET_RUNTIME_PM_OPS’
  343 |  .runtime_resume = resume_fn, \
      |                    ^~~~~~~~~

Signed-off-by: Jarkko Nikula <jarkko.nikula@linux.intel.com>