media: i2c: fix comiple error
Compile error:
drivers/media/i2c/ar0234.c: In function 'ar0234_set_ctrl':
drivers/media/i2c/ar0234.c:508:3: error: a label can only be part of a
statement and a declaration is not a statement
  508 |   u64 reg;
      |   ^~~

Fixes: 35d594ef7f79 ("media: i2c: Add ar0234 camera sensor driver")
Signed-off-by: Lili Li <lili.li@intel.com>