can: m_can: Fix missing closing parenthesis
Don't do quick last minute amending changes to the commit, at least
without a build test...

drivers/net/can/m_can/m_can.c: In function m_can_isr:
drivers/net/can/m_can/m_can.c:959:37: error: expected ) before return
  959 |  if (pm_runtime_suspended(cdev->dev)
      |     ~                               ^

Reported-by: Bottini, Michael A <michael.a.bottini@intel.com>
Signed-off-by: Jarkko Nikula <jarkko.nikula@linux.intel.com>