ASoC: Intel: Skylake: Fix Kconfig dependency
Commit e4746d94d00c ("ASoC: Intel: Skylake: Introduce HDA codec init and
exit routines") introduced HDA codec init routine which depends on SND_HDA.
If SND_SOC_INTEL_SKYLAKE_HDAUDIO_CODEC is enabled, it will be implitly
selected by SND_SOC_HDAC_HDA; otherwise, select SND_HDA explicitly to fix
following compile error:
ERROR: modpost: "snd_hda_codec_device_init" [sound/soc/intel/skylake/snd-soc-skl.ko] undefined!

Fixes: e4746d94d00c ("ASoC: Intel: Skylake: Introduce HDA codec init and exit routines")
Signed-off-by: Lili Li <lili.li@intel.com>