pwm: pwm-dwc: Fix link error on 32-bit ARM and older GCC-9
PWM core has switched to 64-bit period and duty_cycle. That change
caused a following link error when building for 32-bit ARM using
arm-linux-gnueabihf-gcc-9:

arm-linux-gnueabihf-ld: drivers/pwm/pwm-dwc.o: in function `dwc_pwm_apply':
pwm-dwc.c:(.text+0x450): undefined reference to `__aeabi_uldivmod'
arm-linux-gnueabihf-ld: pwm-dwc.c:(.text+0x498): undefined reference to `__aeabi_uldivmod'

Fix this by using DIV_ROUND_CLOSEST_ULL() which is explicitly for u64
dividents.

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Jarkko Nikula <jarkko.nikula@linux.intel.com>