VHM: fix allmodconfig compilation
The following symbols were not exported causing link error when building
i915/gvt driver as module.

ERROR: "acrn_ioreq_destroy_client" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "acrn_ioreq_attach_client" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "vhm_inject_msi" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "add_memory_region" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "del_memory_region" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "acrn_ioreq_complete_request" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "acrn_ioreq_intercept_bdf" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "find_get_vm" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "vhm_get_vm_info" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "acrn_ioreq_del_iorange" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "acrn_ioreq_get_reqbuf" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "write_protect_page" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "acrn_ioreq_add_iorange" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "put_vm" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "acrn_ioreq_create_client" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
ERROR: "vhm_vm_gpa2hpa" [drivers/gpu/drm/i915/gvt/acrngt.ko] undefined!
make[1]: *** [__modpost] Error 1
make: *** [modules] Error 2

Singed-off-by: Fei Yang <fei.yang@intel.com>