ice: fix: Fix ice_pin_desc_e10t compile error
Compile error:
drivers/net/ethernet/intel/ice/ice_ptp.c:11:2: error: braces around scalar initializer [-Werror]
   11 |  { "GNSS",  GNSS, PTP_PF_EXTTS, 0, { 0, } },
      |  ^
drivers/net/ethernet/intel/ice/ice_ptp.c:11:2: note: (near initialization for ‘ice_pin_desc_e810t[0].flags’)
drivers/net/ethernet/intel/ice/ice_ptp.c:12:2: error: braces around scalar initializer [-Werror]
   12 |  { "SMA1",  SMA1, PTP_PF_NONE, 1, { 0, } },
      |  ^
drivers/net/ethernet/intel/ice/ice_ptp.c:12:2: note: (near initialization for ‘ice_pin_desc_e810t[1].flags’)
drivers/net/ethernet/intel/ice/ice_ptp.c:13:2: error: braces around scalar initializer [-Werror]
   13 |  { "U.FL1", UFL1, PTP_PF_NONE, 1, { 0, } },
      |  ^
drivers/net/ethernet/intel/ice/ice_ptp.c:13:2: note: (near initialization for ‘ice_pin_desc_e810t[2].flags’)
drivers/net/ethernet/intel/ice/ice_ptp.c:14:2: error: braces around scalar initializer [-Werror]
   14 |  { "SMA2",  SMA2, PTP_PF_NONE, 2, { 0, } },
      |  ^
drivers/net/ethernet/intel/ice/ice_ptp.c:14:2: note: (near initialization for ‘ice_pin_desc_e810t[3].flags’)
drivers/net/ethernet/intel/ice/ice_ptp.c:15:2: error: braces around scalar initializer [-Werror]
   15 |  { "U.FL2", UFL2, PTP_PF_NONE, 2, { 0, } },
      |  ^
drivers/net/ethernet/intel/ice/ice_ptp.c:15:2: note: (near initialization for ‘ice_pin_desc_e810t[4].flags’)

Fixes: 325b2064d00a ("ice: Implement support for SMA and U.FL on E810-T")
Signed-off-by: Lili Li <lili.li@intel.com>