init/Kconfig: Fix MODULE_SIG dependency
MODULE_SIG is dependent on MODULE_SIG_FORMAT. Without this dependecy
kernel build fails with error -

   kernel/module_signing.o: In function `mod_verify_sig':
   module_signing.c:(.text+0x4e): undefined reference to `mod_check_sig'

Fix it.

Fixes: 61e504af5fcb ("ANDROID: Revert "Merge tag 'modules-for-v5.4' of git://git.kernel.org/pub/scm/linux/kernel/git/jeyu/linux"")
Signed-off-by: Pankaj Bharadiya <pankaj.laxminarayan.bharadiya@intel.com>