pwm: pwm-dwc: Fix build error when !CONFIG_PM_SLEEP && CONFIG_PM
Fix following build error when CONFIG_PM is set but CONFIG_PM_SLEEP is
not:

drivers/pwm/pwm-dwc.c:334:21: error: ‘dwc_pci_runtime_suspend’ undeclared here (not in a function); did you mean ‘pm_runtime_suspend’?
  334 |  SET_RUNTIME_PM_OPS(dwc_pci_runtime_suspend,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~
./include/linux/pm.h:342:21: note: in definition of macro ‘SET_RUNTIME_PM_OPS’
  342 |  .runtime_suspend = suspend_fn, \
      |                     ^~~~~~~~~~
drivers/pwm/pwm-dwc.c:335:7: error: ‘dwc_pci_runtime_resume’ undeclared here (not in a function); did you mean ‘pm_runtime_resume’?
  335 |       dwc_pci_runtime_resume, NULL)
      |       ^~~~~~~~~~~~~~~~~~~~~~
./include/linux/pm.h:343:20: note: in definition of macro ‘SET_RUNTIME_PM_OPS’
  343 |  .runtime_resume = resume_fn, \
      |                    ^~~~~~~~~

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Jarkko Nikula <jarkko.nikula@linux.intel.com>